### ISSUE TITLE
EB nagios integration - check paths for broker_module

### ISSUE THREAD

**Issue by critzo** [m-lab/prometheus-nagios-exporter#4]
Setup instructions in the [Readme](https://github.com/m-lab/prometheus-nagios-exporter#setup) suggest adding this line to /etc/nagios3/nagios.cfg:
```broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus```

However, EB's nagios-config specifies this path for the livestats plugin:
```broker_module=/etc/alternatives/omd/lib/mk-livestatus/livestatus.o /var/lib/nagios3/rw/live```

This issue is to confirm that the path for the mk-livestats plugin is ok as is, or to make alterations to prometheus-nagios-exporter if needed, based on the actual path on EB.

@stephen-soltesz does anything need to change in the exporter based on this information?

**Comment by stephen-soltesz** [comment]
The README is meant as an example for someone who doesn't have the livestatus plugin configured yet.

Since we do, no extra configuration of nagios itself should be necessary.

Just pass the actual livestatus path to the `nagios_exporter.py --path /var/lib/nagios3/rw/live`
